version: '3'
services:
  mysql:
    image: $MYSQL_IMAGE
    container_name: mysql
    restart: always
    env_file:
      - ./data/env/mysql.env
    volumes:
      - ./config/my.cnf:/etc/my.cnf
      - ./data/mysql:/var/lib/mysql
      - ./data/initsql/:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    networks:
      weiyan_net:

  redis:
    image: $REDIS_IMAGE
    container_name: redis
    restart: always
    volumes:
      - "./data:/data"
      - "./config/redis.conf:/usr/local/etc/redis/redis.conf"
    command:
      "redis-server /usr/local/etc/redis/redis.conf"
    depends_on:
      - mysql
    networks:
      weiyan_net:

  rabbitmq:
    image: $RABBITMQ_IMAGE
    container_name: rabbitmq
    restart: always
    depends_on:
      - redis
    networks:
      weiyan_net:
  
  nacos:
    image: $NACOS_IMAGE
    container_name: nacos-server
    restart: always
    env_file:
      - ./data/env/nacos-mysql.env
    volumes:
      - ./data/log/:/home/nacos/logs
    ports:
      - "8848:8848"
      # - "9848:9848"
      # - "9555:9555"
    depends_on:
      - node
    networks:
      weiyan_net:
  
  application:
    image: $PLATFORM
    container_name: application
    restart: always
    volumes:
      - "./data:/data"
    entrypoint: 
      - "/bin/sh"
      - "-c"
      - "java -jar -Dfile.encoding=UTF-8 /applications/application.jar --spring.profiles.active=dc1 --spring.rabbitmq.host=rabbitmq"
    depends_on:
      - rabbitmq
    networks:
      weiyan_net:

  gateway:
    image: $PLATFORM
    container_name: gateway
    restart: always
    entrypoint: 
      - "/bin/sh"
      - "-c"
      - "java -jar -Dfile.encoding=UTF-8 /applications/gateway.jar --spring.profiles.active=dc1 --server.port=8080"
    depends_on:
      - application
    networks:
      weiyan_net:

  nginx:
    image: $WEB_MANAGE
    container_name: manage-web
    restart: always
    volumes:
      - "./config/default.conf:/etc/nginx/conf.d/default.conf"
      - "./data:/data"
    ports:
      - "30080:80"
    depends_on:
      - gateway
    networks:
      weiyan_net:

  node:
    network_mode: "host"
    image: $NODE
    container_name: node
    restart: "always"
    ports:
      - "50050:50050"
      - "6666:6666"
      - "10120:12120"
      - "10121:12121"
    volumes:
      - ./config:/app/config
      - ./data:/data
    entrypoint:
      - "/bin/bash"
      - "-c"
      - "./primihub-node --service_port=50050  --node_id=node2 --config=/app/config/node2.yaml"
    depends_on:
      - redis

networks:
  weiyan_net:
    driver: bridge