
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: redis
  namespace: {{ $.Release.Namespace }}
  labels:
    name: redis
  annotations: {}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
        name: redis
    spec:
      volumes:
        - name: volume-inx7a
          configMap:
            name: redis-config
            items:
              - key: redis.conf
                path: redis.conf
            defaultMode: 420
      containers:
        - name: redis
          image: 'registry.cn-beijing.aliyuncs.com/primihub/redis:7'
          command:
            - redis-server
          args:
            - /usr/local/etc/redis/redis.conf
          resources: {}
          volumeMounts:
            - name: volume-inx7a
              mountPath: /usr/local/etc/redis/redis.conf
              subPath: redis.conf
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      enableServiceLinks: false
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
