- block:
  - name: setup docker
    become: true
    tags: config_docker
    shell: |
      tee /etc/docker/daemon.json <<-'EOF'
      {
          "data-root":"/data/docker",
          "log-opts":{
              "max-size":"100m",
              "max-file":"1"
          },
          "registry-mirrors":[
              "https://hub-mirror.c.163.com",
              "https://mirror.baidubce.com",
              "https://docker.mirrors.ustc.edu.cn",
              "https://registry.docker-cn.com"
          ]
      }
      EOF

      systemctl daemon-reload && systemctl restart docker

  - name: check state
    become: true
    tags: config_docker
    shell: |
      docker info


  - name: restart docker
    become: true
    systemd:
      name: docker
      state: restarted
      enabled: yes
    tags: config_docker
    ignore_errors: true


  - name: restart docker by systemctl
    become: true
    shell: systemctl restart docker
    tags: config_docker
    ignore_errors: true
