version: 1.0

node: "node2"
location: "YOUR_HOST_IP"
grpc_port: 50050
use_tls: 0

redis_meta_service:
  redis_addr: "REDIS_HOST_IP:6379"
  use_redis: True
  redis_password: "primihub"

certificate:
  root_ca: "/tmp/cert/ca.crt"
  key: "/tmp/cert/node2.key"
  cert: "/tmp/cert/node2.crt"

datasets:
  # ABY3 LR test case datasets
  - description: "train_party_2"
    model: "csv"
    source: "/tmp/train_party_2.csv" 
  - description: "test_party_2"
    model: "csv"
    source: "/tmp/test_party_2.csv"
  
  # MNIST test case datasets
  - description: "test_party_2_self"
    model: "csv"
    source: "/tmp/falcon/dataset/MNIST/input_2" 
  - description: "test_party_2_next"
    model: "csv"
    source: "/tmp/falcon/dataset/MNIST/input_0" 
  
  #  FL xgb test case datasets
  - description: "guest_dataset"
    model: "csv"
    source: "/tmp/FL/wisconsin_guest.data" 
  - description: "breast_2"
    model: "csv"
    source: "/tmp/FL/wisconsin.data"
  
  # PSI test caset datasets
  - description: "psi_client_data"
    model: "csv"
    source: "/tmp/client_e.csv"

  - description: "train_hetero_xgb_guest"
    model: "csv"
    source: "/tmp/FL/hetero_xgb/train/train_breast_cancer_guest.csv"
  - description: "test_hetero_xgb_guest"
    model: "csv"
    source: "/tmp/FL/hetero_xgb/test/test_breast_cancer_guest.csv"

localkv: 
  model: "leveldb"
  path: "/data/localdb2"

p2p:
  bootstrap_nodes:
    - "/ip4/172.28.1.13/tcp/4001/ipfs/QmP2C45o2vZfy1JXWFZDUEzrQCigMtd4r3nesvArV8dFKd"
    - "/ip4/172.28.1.13/tcp/4001/ipfs/QmdSyhb8eR9dDSR5jjnRoTDBwpBCSAjT7WueKJ9cQArYoA"
  multi_addr: "/ip4/172.28.1.10/tcp/8888"
  dht_get_value_timeout:  120

notify_server: 0.0.0.0:6666
