
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nacos
  namespace: {{ $.Release.Namespace }}
  labels:
    name: nacos
  annotations: {}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nacos
  template:
    metadata:
      labels:
        name: nacos
    spec:
      initContainers:
        - name: init
          image: busybox
          command: ['sh', '-c', 'until telnet mysql 3306; do echo waiting for mysql; sleep 1; done;']
      containers:
        - name: nacos
          image: {{ $.Values.nacos.image }}
          env:
            - name: TZ
              value: Asia/Shanghai
          ports:
            - name: tcp1
              containerPort: 8848
              protocol: TCP
            - name: tcp2
              containerPort: 9848
              protocol: TCP
            - name: tcp3
              containerPort: 9849
              protocol: TCP
          env:
            - name: PREFER_HOST_MODE
              value: hostname
            - name: MODE
              value: standalone
            - name: SPRING_DATASOURCE_PLATFORM
              value: mysql
            - name: MYSQL_SERVICE_HOST
              value: mysql
            - name: MYSQL_SERVICE_DB_NAME
              value: nacos_config
            - name: MYSQL_SERVICE_PORT
              value: '3306'
            - name: MYSQL_SERVICE_USER
              value: primihub
            - name: MYSQL_SERVICE_PASSWORD
              value: primihub@123
            - name: MYSQL_SERVICE_DB_PARAM
              value: >-
                characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false
            
          resources: {}
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
