kind: Service
apiVersion: v1
metadata:
  name: fusion
  namespace: {{ $.Release.Namespace }}
  labels:
    name: fusion
  annotations:
    workload: fusion
spec:
  ports:
    - name: fusion
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    name: fusion
  type: ClusterIP
  # sessionAffinity: None
  # externalTrafficPolicy: Cluster
  # ipFamilies:
  #   - IPv4
  # ipFamilyPolicy: SingleStack
  # internalTrafficPolicy: Cluster
