{{- range $tmpindex, $app := until ( int $.Values.fusion.num )}} 
{{- $index := add $tmpindex 1 -}}
kind: Service
apiVersion: v1
metadata:
  name: fusion{{ $index }}
  namespace: {{ $.Release.Namespace }}
  labels:
    name: fusion{{ $index }}
  annotations:
    workload: fusion{{ $index }}
spec:
  ports:
    - name: fusion{{ $index }}
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    name: fusion{{ $index }}
  type: ClusterIP
  # sessionAffinity: None
  # externalTrafficPolicy: Cluster
  # ipFamilies:
  #   - IPv4
  # ipFamilyPolicy: SingleStack
  # internalTrafficPolicy: Cluster
---
{{- end }}
