- name: install docker, centos
  block:
    - name: add docker yum repo, centos
      get_url:
        url: http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/aliyun-docker-ce.repo

    - name: install docker-ce, centos
      yum:
        state: present
        name: "{{ pkg }}"
        allow_downgrade: yes
      vars:
        pkg:
          - docker-ce-19.03.5
          - docker-ce-cli-19.03.5
          - containerd.io-1.2.10
  tags: install-docker
  when: 
  - ansible_distribution == 'CentOS'
  - mode == 'online'

- name: exec apt update
  shell: apt update
  ignore_errors: true
  tags: install-docker
  when:
  - ansible_distribution == 'Ubuntu'
  - mode == 'online'

- block:
    - name: install deps online focal
      shell: |
        apt install -y \
            apt-transport-https \
            ca-certificates \
            curl \
            gnupg-agent \
            software-properties-common \
            python-apt

    - name: ubuntu, add apt key
      apt_key:
        url: https://mirrors.aliyun.com/docker-ce/linux/ubuntu/gpg
        state: present

    - name: add docker deb
      apt_repository:
        filename: docker
        repo: deb [arch=amd64] http://mirrors.aliyun.com/docker-ce/linux/ubuntu focal stable

    - name: exec apt update
      shell: apt update
      ignore_errors: true

    - name: exec intall docker  
      shell: apt install -y --allow-downgrades docker-ce=5:19.03.15~3-0~ubuntu-bionic docker-ce-cli=5:19.03.15~3-0~ubuntu-bionic containerd.io=1.2.10-2
  
  tags: install-docker
  when:
  - ansible_distribution == 'Ubuntu'
  - mode == 'online'
  - ansible_distribution_version == '20.04'

- block:
    - name: install deps online 1804
      vars:
        ansible_python_interpreter: /usr/bin/python3
      shell: |
        apt install -y \
            apt-transport-https \
            ca-certificates \
            curl \
            gnupg-agent \
            software-properties-common \
            python-apt

    - name: ubuntu, add apt key
      apt_key:
        url: https://mirrors.aliyun.com/docker-ce/linux/ubuntu/gpg
        state: present

    - name: add docker deb
      vars:
        ansible_python_interpreter: /usr/bin/python3
      apt_repository:
        filename: docker
        repo: deb [arch=amd64] http://mirrors.aliyun.com/docker-ce/linux/ubuntu bionic stable

    - name: exec apt update
      shell: apt update
      ignore_errors: true

    - name: exec intall docker  
      shell: apt install -y --allow-downgrades docker-ce=5:19.03.15~3-0~ubuntu-bionic docker-ce-cli=5:19.03.15~3-0~ubuntu-bionic containerd.io=1.2.10-2
  
  tags: install-docker
  when:
  - ansible_distribution == 'Ubuntu'
  - mode == 'online'
  - ansible_distribution_version == '18.04'

- block:
    - name: install deps online 1604
      shell: |
        apt install -y \
            apt-transport-https \
            ca-certificates \
            curl \
            gnupg-agent \
            software-properties-common \
            python-apt

    - name: ubuntu, add apt key
      apt_key:
        url: https://mirrors.aliyun.com/docker-ce/linux/ubuntu/gpg
        state: present

    - name: add docker deb
      apt_repository:
        filename: docker
        repo: deb [arch=amd64] http://mirrors.aliyun.com/docker-ce/linux/ubuntu xenial stable
            
    - name: exec apt update
      shell: apt update
      ignore_errors: true

    - name: exec intall docker  
      shell: apt install -y --allow-downgrades docker-ce=5:19.03.15~3-0~ubuntu-bionic docker-ce-cli=5:19.03.15~3-0~ubuntu-bionic containerd.io=1.2.10-2
  
  tags: install-docker
  when:
  - ansible_distribution == 'Ubuntu'
  - mode == 'online'
  - ansible_distribution_version == '16.04'  

# 1604 xenial , 1804 bionic, 2004 focal

