apiVersion: v1
kind: ConfigMap
metadata:
  name: node-configmap
  namespace: {{ .Release.Namespace }}
data:
  primihub_node0.yaml: |-
    version: 1.0

    node: "node0"
    location: "primihubnode"
    grpc_port: 50050
    use_tls: false

    proxy_server:
      mode: "grpc"
      ip:  "primihubnode"
      port: 50050
      use_tls: false

    meta_service:
      mode: "grpc"
      ip: "fusion1"
      port: 9099
      use_tls: false

    datasets:
      # ABY3 LR test case datasets

  primihub_node1.yaml: |-
    version: 1.0

    node: "node1"
    location: "primihubnode"
    grpc_port: 50051
    use_tls: false

    proxy_server:
      mode: "grpc"
      ip:  "primihubnode"
      port: 50051
      use_tls: false

    meta_service:
      mode: "grpc"
      ip: "fusion2"
      port: 9099
      use_tls: false

    datasets:
      # ABY3 LR test case datasets
      

  primihub_node2.yaml: |-
    version: 1.0

    node: "node2"
    location: "primihubnode"
    grpc_port: 50052
    use_tls: false

    proxy_server:
      mode: "grpc"
      ip:  "primihubnode"
      port: 50052
      use_tls: false

    meta_service:
      mode: "grpc"
      ip: "fusion3"
      port: 9099
      use_tls: false

    certificate:
      root_ca: "/tmp/cert/ca.crt"
      key: "/tmp/cert/node2.key"
      cert: "/tmp/cert/node2.crt"

    datasets:
      # ABY3 LR test case datasets