- block:
    - name: apt update action,  ubuntu
      shell: apt update
      ignore_errors: true
    - name: install deps, ubuntu
      shell: apt install -y  socat conntrack ebtables ipset chrony
    - name: enable chrony , ubuntu
      shell: systemctl enable --now chrony
    - name: timezone set , ubuntu
      shell: timedatectl set-timezone Asia/Shanghai
    - name: install software-properties-common
      shell: apt install -y software-properties-common
    - name: add resolve.conf
      lineinfile:
        path: /etc/resolv.conf
        line: nameserver 8.8.8.8
        state: present
  tags: install-deps
  when:
  - ansible_distribution == 'Ubuntu'
  - mode == 'online'


# - name: check python version
#   shell: python3 --version
#   register: python_version

# - block:
#     - name: install python3.8
#       shell: apt intstall python3.8
#   when:
#   - mode == 'online'
#   - python_version.rc != 0