version: '3'
services:
  mysql:
    image: $MYSQL_IMAGE
    container_name: mysql
    restart: always
    env_file:
      - ./data/env/mysql.env
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./config/my.cnf:/etc/my.cnf
      - ./data/mysql:/var/lib/mysql
      - ./data/initsql/:/docker-entrypoint-initdb.d/
    # ports:
    #   - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      primihub_net:

  redis:
    image: $REDIS_IMAGE
    container_name: redis
    restart: always
    volumes:
      - "./data:/data"
      - "./config/redis.conf:/usr/local/etc/redis/redis.conf"
    command:
      "redis-server /usr/local/etc/redis/redis.conf"
    ports:
      - "6379:6379"
    networks:
      primihub_net:

  rabbitmq:
    image: $RABBITMQ_IMAGE
    container_name: rabbitmq
    restart: always
    networks:
      primihub_net:
  
  nacos:
    image: $NACOS_IMAGE
    container_name: nacos-server
    restart: always
    env_file:
      - ./data/env/nacos-mysql.env
    volumes:
      - ./data/log/:/home/nacos/logs
    ports:
      - "8848:8848"
      # - "9848:9848"
      # - "9555:9555"
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail -s http://localhost:8848/nacos"]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      primihub_net:

  fusion:
    image: $FUSION
    container_name: fusion
    restart: always
    environment:
      - TZ=Asia/Shanghai
    entrypoint: 
      - "/bin/sh"
      - "-c"
      - "java -jar -Dfile.encoding=UTF-8 /applications/fusion.jar --spring.profiles.active=dc --server.port=8080 --spring.datasource.druid.url='jdbc:mysql://mysql:3306/fusion?characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&allowMultiQueries=true&serverTimezone=Asia/Shanghai&useSSL=false'"
    ports:
      - "8080:8080"
    networks:
      primihub_net:
  
  application:
    image: $PLATFORM
    container_name: application
    restart: always
    volumes:
      - "./data:/data"
    environment:
      - TZ=Asia/Shanghai
    entrypoint: 
      - "/bin/sh"
      - "-c"
      - "java -jar -Dfile.encoding=UTF-8 /applications/application.jar --spring.profiles.active=dc1 --spring.rabbitmq.host=rabbitmq"
    depends_on:
      nacos:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -O - -q http://localhost:8090/runFeign"]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      primihub_net:

  gateway:
    image: $PLATFORM
    container_name: gateway
    restart: always
    environment:
      - TZ=Asia/Shanghai
    entrypoint: 
      - "/bin/sh"
      - "-c"
      - "java -jar -Dfile.encoding=UTF-8 /applications/gateway.jar --spring.profiles.active=dc1 --server.port=8080"
    depends_on:
      - application
    networks:
      primihub_net:

  nginx:
    image: $WEB_MANAGE
    container_name: manage-web
    restart: always
    volumes:
      - "./config/default.conf:/etc/nginx/conf.d/default.conf"
      - "./data:/data"
    ports:
      - "30080:80"
    depends_on:
      - gateway
    networks:
      primihub_net:

  node:
    shm_size: '6gb'
    network_mode: "host"
    image: $NODE
    container_name: node
    restart: "always"
    ports:
      - "50050:50050"
      # - "6666:6666"
    volumes:
      - ./config/node0.yaml:/app/config/node0.yaml
      - ./data:/data
    environment:
      - TZ=Asia/Shanghai
    entrypoint:
      - "/bin/bash"
      - "-c"
      - "./primihub-node --service_port=50050  --node_id=node0 --config=/app/config/node0.yaml"
    depends_on:
      - redis

  loki:
    image: $LOKI_IMAGE
    container_name: loki
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - LANG=zh_CN.UTF-8
    volumes:
      - ./data:/data
    ports:
      - 3100:3100
    networks:
      primihub_net:

networks:
  primihub_net:
    driver: bridge