{{- range $tmpindex, $app := until ( int $.Values.application.num )}} 
{{- $index := add $tmpindex 1 -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: application{{ $index }}
  namespace: {{ $.Release.Namespace }}
  labels:
    name: application{{ $index }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: application{{ $index }}
  template:
    metadata:
      labels:
        name: application{{ $index }}
    spec:
      volumes:
        - name: application-pvc-{{ $index }}
          persistentVolumeClaim:
            claimName: primihub-volume
      containers:
        - name: application{{ $index }}
          image: {{ $.Values.application.image }}
          env:
            - name: NAMESPACE
              value: {{ $.Release.Namespace }}
          command:
            - java
          args:
            - '-jar'
            - '-Dfile.encoding=UTF-8'
            - /applications/application.jar
            - '--server.port=8080'
            - '--spring.profiles.active=demo{{ $index }}'
            - '--spring.rabbitmq.host=rabbitmq{{ $index }}'
            - '--spring.cloud.nacos.discovery.server-addr=nacos:8848'
            - '--nacos.config.server-addr=nacos:8848'
            {{ if eq $index 1 }}
            - '--spring.cloud.nacos.discovery.namespace=46b6b568-e6ae-45ca-baa1-819932fc8947'
            - '--nacos.config.namespace=46b6b568-e6ae-45ca-baa1-819932fc8947'
            {{ else if eq $index 2 }}
            - '--spring.cloud.nacos.discovery.namespace=71843998-b60a-42ed-81d7-c3c9940d11c0'
            - '--nacos.config.namespace=71843998-b60a-42ed-81d7-c3c9940d11c0'
            {{ else if eq $index 3 }}
            - '--spring.cloud.nacos.discovery.namespace=35674f9d-3369-42f6-9f30-c8de2535adc6'
            - '--nacos.config.namespace=35674f9d-3369-42f6-9f30-c8de2535adc6'
            {{ end }}
          volumeMounts:
            - name: application-pvc-{{ $index }}
              mountPath: /data
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 10
  # serviceName: application-headless
  # volumeClaimTemplates:
  #   - metadata:
  #       name: application-pvc-{{ $index }}
  #       namespace: {{ $.Release.Namespace }}
  #     spec:
  #       accessModes: ["ReadWriteOnce"]
  #       storageClassName: "managed-nfs-storage"
  #       resources:
  #         requests:
  #           storage: 10Gi

---
{{- end }}
